### ISSUE TITLE
tf_frame ignores tf2 static latch transforms 

### ISSUE THREAD

**Issue by rnunziata** [ros/geometry2#33]
tf_frame ignores tf2 static latch transforms. tf2 static latch transforms do not show in tf_frame graph.

```
int main(int argc, char **argv)
{
  ros::init(argc, argv, "robot_odometry");
  tf2_ros::StaticTransformBroadcaster static_broadcaster;

  geometry_msgs::TransformStamped msg2;

  msg2.header.stamp = ros::Time::now();
  msg2.transform.translation.z = 0.1;
  msg2.transform.rotation.w =  1;
  msg2.transform.translation.z = 0.1;
  msg2.transform.translation.y = 0.13; 
  msg2.transform.translation.x = 0.13; 
  msg2.header.frame_id = "base_link";   
  msg2.child_frame_id  = "right";;
  static_broadcaster.sendTransform(msg2);


  ros::spin();
  return 0;
}



<?xml version="1.0"?>
<robot name="rrbot">
   <link name='base_link'>
      <visual name='visual'>
        <geometry>
          <box  size=".4 .2 .1"/>
        </geometry>
      </visual>
  </link>


  <link name="right">
    <visual name="visual">
      <origin xyz="0.13 0.13 0.1" />
      <geometry>
        <cylinder  length="0.5" radius="0.5"/>
      </geometry>
    </visual>
  </link>

  <joint type="fixed" name="joint2">
    <origin xyz="0.13 0.13 0.1" />
    <parent link="base_link"/>
    <child link="right"/>
  </joint>

</robot>
```

Also to note : no matter how many transforms I send weather independently or via vector only the last transform is published. The model was updated to new links in this case.

```
  std::vector<geometry_msgs::TransformStamped> v1;
  v1.push_back(msg1);
  v1.push_back(msg2);
      .
      .
      .
  static_broadcaster.sendTransform(v1);
```

**Comment by tfoote** [comment]
Please update this description to use proper names of components and provide an example of your problem that is reproducible with the expected output and the failing output.  Until I can reproduce your problem in a minimal use case I cannot understand it or verify that I have fixed it.

**Comment by tfoote** [comment]
Without more clarification I cannot reproduce part 1. 

I cannot reproduce the vector issue. sending two transforms left and right results in two messages being sent. 

output of `rostopic echo /tf_static`

```
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1425434362
        nsecs: 787121440
      frame_id: base_link
    child_frame_id: right
    transform: 
      translation: 
        x: 0.13
        y: 0.13
        z: 0.1
      rotation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1425434362
        nsecs: 787123264
      frame_id: base_link
    child_frame_id: left
    transform: 
      translation: 
        x: 0.13
        y: 0.13
        z: 0.1
      rotation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
---
```
